#   ------------------------------------------------------------------------   #
#   Site Settings
#   ------------------------------------------------------------------------   #

title:          "HTML Prototype"

description:    ""

baseurl:        ""

url:            ""

source:         "src/templates"

timezone:       "Europe/Brussels"





#   ------------------------------------------------------------------------   #
#   Build Settings
#   ------------------------------------------------------------------------   #

markdown:       kramdown

permalink:      /:year/:month/:title
